version: '3.5'
services:
  postgis:
    image: andordevops/postgis:1.0
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis
      - POSTGRES_DB=tsig
    ports:
      - 5432:5432
    restart: on-failure

  cargador:
    build: ./cargador/
    volumes:
      - ./cargador/scripts:/scripts:ro
    depends_on:
      - postgis

  wildfly:
    build: ./wildfly/
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
      - ./wildfly/binarios/bondisuy.ear:/opt/jboss/wildfly/standalone/deployments/bondisuy.ear:ro
      - ./wildfly/binarios/geoserver.war:/opt/jboss/wildfly/standalone/deployments/geoserver.war:ro
    depends_on:
      - cargador
